### ISSUE TITLE
Fine-tuning versus Retraining

### ISSUE THREAD

**Issue by leebean337** [MarvinLvn/voice-type-classifier#15]
I am interested in fine-tuning the VTC model (rather than retraining it) such that only the outer LSTM and FF layers are affected. Is there a way to specify this within the config.yml file? Thank you!

**Comment by MarvinLvn** [comment]
In the current state of the code, it is unfortunately not possible to specify which layers must be retrained.
Closing this issue for now

**Comment by fabiocat93** [comment]
Hello, 
I am trying to figure out how to fine-tune the vtc model. Is there any example code somewhere? @leebean337 how did you manage fine-tuning? And @MarvinLvn is it possible to load the vtc model with the latest version of pyannote.audio? Or do you maybe have a newer version of the model trained with a more recent pyannote.audio? Thank you
