### ISSUE TITLE
./apply.sh: Something went wrong when applying the model

### ISSUE THREAD

**Issue by sarpu** [MarvinLvn/voice-type-classifier#16]
Hello,

I am running into an issue while going through the **applying** step of the docs. When I try to run ```./apply.sh /home/sarp/projects/0396_scrubbed.wav``` I get the following output:

```{bash}
(pyannote) sarp@sarp:~/projects/voice_type_classifier$ ./apply.sh /home/sarp/projects/0396_scrubbed.wav 
Creating config for pyannote.
Done creating config for pyannote.
Test set: 0it [00:00, ?it/s]./apply.sh: line 145: 28491 Killed                  pyannote-audio mlt apply --$DEVICE --batch=$BATCH --subset=test --parallel=8 $VAL_DIR ${bn}_protocol.SpeakerDiarization.All
Something went wrong when applying the model
Aborting.
```

I have attached the packages in my conda environment, output of  ```conda info```, the output of soxi on the file I am using and information about my cpu (I am trying to run it on cpu on my machine). I am on an ```Ubuntu 16.04.7 LTS``` machine. Thank you very much in advance for any help!

[soxi_info.txt](https://github.com/MarvinLvn/voice-type-classifier/files/5227344/soxi_info.txt)
[cpu.txt](https://github.com/MarvinLvn/voice-type-classifier/files/5227365/cpu.txt)
[conda_info.txt](https://github.com/MarvinLvn/voice-type-classifier/files/5227340/conda_info.txt)
[packages.txt](https://github.com/MarvinLvn/voice-type-classifier/files/5227329/packages.txt)

**Comment by MarvinLvn** [comment]
Hi Sarp,

It seems the model has been launched but your system just killed it.
This is likely due to a memory issue.

To solve this, you can try to reduce the batch size by typing :
```
./apply.sh /home/sarp/projects/0396_scrubbed.wav --batch=16
```
The default size is set to 32, you can try values like 16, 8 or 4.

Let me know if this solves your issue. In the meantime, I'll try to make the code more robust to these memory issues.

**Comment by sarpu** [comment]
So I tried ```--batch=4```, but it still gets killed. And yes, ```dmesg``` shows that it is a memory issue:

```{bash}
[93149.439833] [ 1349]  1000  1349  1931973   869562  8744960        0             0 pyannote-audio
[93149.439835] Out of memory: Kill process 1349 (pyannote-audio) score 394 or sacrifice child
[93149.439846] Killed process 1349 (pyannote-audio) total-vm:7727892kB, anon-rss:3478240kB, file-rss:4kB, shmem-rss:4kB
[93149.536547] oom_reaper: reaped process 1349 (pyannote-audio), now anon-rss:0kB, file-rss:0kB, shmem-rss:4kB
```

**Comment by MarvinLvn** [comment]
Hi Sarp,

I think we found the bug that was causing an intense memory usage (More details there https://github.com/pyannote/pyannote-audio/issues/443).

Could you do the following :
1) Delete the voice-type-classifier as well as your conda env
2) Follow the installation steps
3) Reapply the model

**Comment by sarpu** [comment]
I closed all other programs on my machine and let it run for a few hours, but it still got killed. I will try it on a more powerful machine and report back.

**Comment by MarvinLvn** [comment]
Good thing there has been progress since the model is running now (before getting killed :() !
Waiting for your updates :)
