### ISSUE TITLE
something went wrong when applying th emodel

### ISSUE THREAD

**Issue by JunzheJosephZhu** [MarvinLvn/voice-type-classifier#17]
./apply.sh ../LENA/OLD_PROTOCOL/03m_IDP/ --device=gpu --batch=1
Creating config for pyannote.
Done creating config for pyannote.
Usage:
  pyannote-audio (sad | scd | ovl | emb | dom) train    [--cpu | --gpu] [options] <root>     <protocol>
  pyannote-audio (sad | scd | ovl | emb | dom) validate [--cpu | --gpu] [options] <train>    <protocol>
  pyannote-audio (sad | scd | ovl | emb | dom) apply    [--cpu | --gpu] [options] <validate> <protocol>
  pyannote-audio -h | --help
  pyannote-audio --version
Something went wrong when applying the model
Aborting.

I followed all the steps in the documentation, and installed pytorch in new environment with conda install -c pytorch pytorch

**Comment by MarvinLvn** [comment]
Hi @JunzheJosephZhu,

It seems that a wrong version of pyannote-audio has been installed. A version that does not support the voice type classifier.

1) Are you sure you followed the steps presented in the [Installation section](https://github.com/MarvinLvn/voice-type-classifier/blob/new_model/docs/installation.md) ?
2) Are you sure, the right conda env has been activated ? Its name should be 'pyannote' and this conda env should be activated asap during the installation steps.
3) I think your error might appear if you ran the installations steps on an old version of the **voice_type_classifier** repo. In which case, the best would be to delete the **voice_type_classifier** folder before going through the installation steps.

What you should expect from the pyannote usage function (if you type **pyannote-audio** in you terminal) is: 

```
Usage:
  pyannote-audio (sad | scd | ovl | emb | dom | mlt) train    [--cpu | --gpu] [options] <root>     <protocol>
  pyannote-audio (sad | scd | ovl | emb | dom | mlt) validate [--cpu | --gpu] [options] <train>    <protocol>
  pyannote-audio (sad | scd | ovl | emb | dom | mlt) apply    [--cpu | --gpu] [options] <validate> <protocol>
  pyannote-audio -h | --help
  pyannote-audio --version
```

Please note the **mlt** (for multilabel) that doesn't appear in the error message you sent me.
I'm currently trying to redownload/reinstall everything from scratch to check that nothing has been broken recently. 
In the meantime, could you please let me know if any of the hypothesis listed above might apply to your case ?

**Comment by MarvinLvn** [comment]
I can confirm that nothing has been broken recently. The code is running smoothly.

**Comment by JunzheJosephZhu** [comment]
Sorry for the confusion, I mistakenly used conda create env pyannote. Thank you for your quick response! Great repo.

**Comment by MarvinLvn** [comment]
Thanks a lot :) 
Don't hesitate to leave me feedback to improve the code !
