### ISSUE TITLE
Conda virtual env error made with the vtc.yml file

### ISSUE THREAD

**Issue by choward232** [MarvinLvn/voice-type-classifier#19]
Running the command in the installation doc "conda env create -f vtc.yml" yields the error:  

Pip subprocess error:
ERROR: Directory 'pyannote-audio/' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

failed

CondaEnvException: Pip failed

This can easily be reproduced by running the above command using the vtc.yml file in the repo.

 I believe the issue lies in the last line: - pyannote-audio/ 
It seems like pyannote audio must be installed using the syntax pyannote.audio, but even manually installing the package through pip install pyannote.audio does not seem to fix the error since when running the apply script later on, an error pops up saying:
pyannote-audio can't be found.
Check that you activated your conda environment and than you installed pyannote-audio.

My suspicion is the old syntax, pyannote-audio, has been hardcoded into the file dependencies but is no longer applicable. This is only my suspicion though and could totally be wrong. Regardless, I would love some guidance on how to fix this. Thanks!

**Comment by MarvinLvn** [comment]
Hi @choward232,

The command 

```
git clone --recurse-submodules https://github.com/MarvinLvn/voice_type_classifier.git
```

is supposed to clone the current git repository as well as its submodules : this should create a **pyannote-audio** directory within the voice_type_classifier directory. And this **pyannote-audio** folder does contain a **setup.py**

In the vtc.yml, the line : 

```
pyannote-audio/
```

installs the pyannote-audio package from source. (I added the **/** to higlight the fact that it is installed from source)

The command :

```
pip install pyannote.audio
```

won't install the right version of the package. Please do not use it. 

I'm not sure what went wrong in your installation, are you sure you did clone this repo by typing : 

```
git clone --recurse-submodules https://github.com/MarvinLvn/voice_type_classifier.git
```

and NOT : 

```
git clone https://github.com/MarvinLvn/voice_type_classifier.git
```

All the steps for installing the repo are described [there](https://github.com/MarvinLvn/voice-type-classifier/blob/new_model/docs/installation.md).
Closing this issue for now as the other users haven't met any trouble installing the package.
Feel free to reopen it if needed.

**Comment by TSSlade** [comment]
@MarvinLvn - I've been having the same issue as choward mentioned above. Here are the relevant portions of the call:
```
conda env create -f vtc.yml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/home/ubuntu/miniconda3/envs/pyannote/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/ubuntu/voice_type_classifier/condaenv.75fvdi6y.requirements.txt']
Pip subprocess output:
Processing ./pyannote-audio
Collecting cachetools>=2.0.0
  Using cached cachetools-4.2.1-py3-none-any.whl (12 kB)
Processing /home/ubuntu/.cache/pip/wheels/18/9e/42/3224f85730f92fa2925f0b4fb6ef7f9c5431a64dfc77b95b39/librosa-0.7.2-py3-none-any.whl
Collecting pandas>=0.18.0
  Using cached pandas-1.2.4-cp37-cp37m-manylinux1_x86_64.whl (9.9 MB)
Collecting pyannote.core==3.7.1
  Using cached pyannote.core-3.7.1-py3-none-any.whl (54 kB)
Collecting pyannote.database==3.0.1
  Using cached pyannote.database-3.0.1-py3-none-any.whl (32 kB)
Collecting pyannote.metrics==2.3
  Using cached pyannote.metrics-2.3-py3-none-any.whl (48 kB)
Collecting pyannote.pipeline==1.5
  Using cached pyannote.pipeline-1.5-py3-none-any.whl (24 kB)
Collecting pyYAML>=3.12
  Using cached PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
Collecting scikit-learn>=0.20.2
  Using cached scikit_learn-0.24.1-cp37-cp37m-manylinux2010_x86_64.whl (22.3 MB)
Collecting sortedcollections>=1.0.1
  Using cached sortedcollections-2.1.0-py3-none-any.whl (9.5 kB)
Collecting sortedcontainers>=2.0.4
  Using cached sortedcontainers-2.3.0-py2.py3-none-any.whl (29 kB)
Collecting soundfile>=0.10.2
  Using cached SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
Collecting tqdm>=4.29.1
  Using cached tqdm-4.60.0-py2.py3-none-any.whl (75 kB)
Collecting tensorboard>=2.0.0
  Using cached tensorboard-2.4.1-py3-none-any.whl (10.6 MB)
Collecting typing_extensions>=3.7.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Processing /home/ubuntu/.cache/pip/wheels/f0/e3/c6/32d30d5eb5292dac352d2fca4ebf393aa94e09b9b8b4b0f341/pescador-2.1.0-py3-none-any.whl
Collecting Pillow>=6.2.1
  Using cached Pillow-8.2.0-cp37-cp37m-manylinux1_x86_64.whl (3.0 MB)
Collecting torch>=1.4.0

Pip subprocess error:
/home/ubuntu/miniconda3/envs/pyannote/.tmpfryvl6b6: line 3: 92650 Killed                  /home/ubuntu/miniconda3/envs/pyannote/bin/python -m pip install -U -r /home/ubuntu/voice_type_classifier/condaenv.75fvdi6y.requirements.txt

failed

CondaEnvException: Pip failed
``` 

I've nuked Miniconda and reinstalled from scratch, I've tried manually installing `pyannote` following their instructions, etc. Not having any luck - any recommendations?

If I manually install all of the packages listed in the `requirements.txt` I can eventually get an environment that contains all the required packages and dependencies, but then I still have the situation that `pyannote-audio` is not detected.
