### ISSUE TITLE
Model not found when executing apply.sh from another folder

### ISSUE THREAD

**Issue by orasanen** [MarvinLvn/voice-type-classifier#2]
When calling apply.sh, the script assumes that the /model/ folder can be found under the current terminal folder from which the call is made, not under the folder where apply.sh is located. This can be circumvented by first cd:ing to the voice-type-classifier folder, and then calling apply.sh, but it would be more conventional if the function could be called from anywhere, and a relative path would be used for finding the model.

**Comment by orasanen** [comment]
The problem also seems to occur when awk is used after pyannote call:
awk: can't open file model/train/BBT_emp.SpeakerDiarization.All.train/validate_SPEECH/BBT_emp.SpeakerDiarization.All.development/apply/0495/files_to_transcribe.SpeakerDiarization.All.test.rttm . Using hard-coded paths at the beginning of apply.sh for the different classes fixes the problem.

**Comment by MarvinLvn** [comment]
Solved, you should now be able to run : 

```
./a/b/c/voice_type_classifier/apply.sh /my/folder/to/wav
```

Note that this will generate the output in the current folder.
