### ISSUE TITLE
windows users!!!

### ISSUE THREAD

**Issue by asrar-khaldey** [MarvinLvn/voice-type-classifier#20]
hi
when running apply.sh command I get the following script and no other files
![3b16716a-8d05-4b23-8af0-7cd19d107a7f](https://user-images.githubusercontent.com/73520777/98854783-b0b5d180-2463-11eb-8a22-ed9699c23a84.JPG)

we also tried to run the command using ubuntu (to create Linux env)
(p.s we are beginners)

**Comment by truegracek** [comment]
Another beginner here, and I'm having a similar problem. I'm using Windows10, manually installed a version of SoX c14.4.2, added the sox folder to my PATH, but still doesn't work. When I run the soxi command, it gives the error, "soxi is not recognized as an internal or external command, operable program or batch file." and when I try to run apply.sh, it says "Sox can't be found. Please install sox before running this script"
I think I installed all the other parts of this library correctly, with all the dependencies...

**Comment by asrar-khaldey** [comment]
Yes I’ve had my share of “Sox cant be found”  but adding Sox to my path using cmd (you have to run PATH and set Sox directory) solved the problem
But still no output :(
I have also tried to run the script with GIT bash/ ubuntu..

________________________________

**Comment by truegracek** [comment]
Thanks, I manually added the sox directory to my path in cmd, and started over to make sure (and now I'm seeing it in the path list), but still having the same issue...

**Comment by MarvinLvn** [comment]
Hi @truegracek and @asrar-khaldey,

Unfortunately, I did not have the opportunity to try the voice type classifier on Windows yet :'(
One wonderful tool that allow Windows users to have a Linux-like distribution is WSL ([installation steps here](https://docs.microsoft.com/en-us/windows/wsl/install-win10)). You shouldn't have any troubles if you install the voice type classifier on WSL (and it'd be useful for other Linux tools/models you might want to use).

Another possibility is to install the repo on [Docker ](https://www.docker.com/) and we're currently working on that. It should be released in a few weeks.

I let this issue opened for now as I'd be very happy to stay in touch with you. Could you let me know if you try installing WSL ?

**Comment by truegracek** [comment]
Hi @MarvinLvn , thanks for your quick and kind response.
I first tried to set up WSL on my local machine and it worked, but I couldn't enable GPU on it, so I managed to set up an Ubuntu system on AWS EC2 and it works well! I still got the sox error (for both cases) and installing it manually solved the problem.
I have an additional question, although not related to this thread.
I kept getting an error when I had spacing in the names of the directories and wav files.
For example, the following:

soxi FAIL formats: can't open input file `/home/ubuntu/voice_type_classifier/voice_data/Charity/Inn': No such file or directory
soxi FAIL formats: can't open input file `Keeper_1213.wav': No such file or directory
soxi FAIL formats: can't open input file `/home/ubuntu/voice_type_classifier/voice_data/Charity/Mother_A': No such file or directory
soxi FAIL formats: can't open input file `Child': No such file or directory
soxi FAIL formats: can't open input file `Of': No such file or directory
soxi FAIL formats: can't open input file `Mine.wav': No such file or directory

The problem didn't go away by wrapping the path with " " Is there any way to get around this other than renaming my files? Would really appreciate your answer.

**Comment by MarvinLvn** [comment]
Hi @truegracek ,

> I first tried to set up WSL on my local machine and it worked, but I couldn't enable GPU on it, so I managed to set up an Ubuntu system on AWS EC2 and it works well! I still got the sox error (for both cases) and installing it manually solved the problem.

I added a line in the installations steps to make it a bit clearer than sox is a required dependency. Thanks a lot for your feedback and congrats for having installed the model ! AWS EC2 is a very good solution too !

> I have an additional question, although not related to this thread.
I kept getting an error when I had spacing in the names of the directories and wav files.
For example, the following:

> soxi FAIL formats: can't open input file /home/ubuntu/voice_type_classifier/voice_data/Charity/Inn': No such file or directory soxi FAIL formats: can't open input file Keeper_1213.wav': No such file or directory
soxi FAIL formats: can't open input file /home/ubuntu/voice_type_classifier/voice_data/Charity/Mother_A': No such file or directory soxi FAIL formats: can't open input file Child': No such file or directory
soxi FAIL formats: can't open input file Of': No such file or directory soxi FAIL formats: can't open input file Mine.wav': No such file or directory

> The problem didn't go away by wrapping the path with " " Is there any way to get around this other than renaming my files? Would really appreciate your answer.

Unfortunately, no. Spaces will be interpreted as the separator by the terminal :'( On Ubuntu, it is usually not recommended to have filenames containing spaces.
One quick way to solve this in bash is : 

```
find /path/to/the/audio/files/containing/spaces/ -depth -name "* *" -execdir rename 's/ /_/g' "{}" \;
```

This command will find all files and directories containing spaces and belonging to  */path/to/the/audio/files/containing/spaces/* and will replace spaces by underscores.

For instance **my audios/audio 123.wav** will become **my_audios/audio_123.wav**
