### ISSUE TITLE
citation unclear in README, arxiv paper doesn't contain info on accepted paper

### ISSUE THREAD

**Issue by alecristia** [MarvinLvn/voice-type-classifier#22]
showing the readme to someone, I realized the only links to papers & code are to ALICE. We should:

- [x] add clearer links to the Interspeech paper which benchmarks this code, 
- [x] correct the bib entry in the README, 
- [x] provide link to arxiv version, 
- [x] update arxiv version to indicate that it has been accepted

**Comment by MarvinLvn** [comment]
Waiting for ArXiV approval.
Thanks for the issue !
