### ISSUE TITLE
CondaEnvException: Pip failed when creating "pyannote"

### ISSUE THREAD

**Issue by ljr10225008** [MarvinLvn/voice-type-classifier#23]
I am a very beginner and when I installed this software I met the following problem. Could anyone help?

I try to install this software on a Ubuntu 20.04 LTS (subsystem installed on windows10). When I come to the step of "conda env create -f vtc.yml" it shows errors like this,
![image](https://user-images.githubusercontent.com/61999816/117953079-c2aff880-b350-11eb-8258-713af7ca0ccb.png)

The python version I used is python 3.8.

Thanks in advance!

**Comment by ljr10225008** [comment]
Problem solved by update python version to 3.8. Pip 2.0.2 can not find cachetools>=2.0.0. Also, librosa version is wrong as well. The newest version work.

**Comment by MarvinLvn** [comment]
Thanks a lot for your issue and solution :)
I'm sure it'll be helpful for other users !
I just updated `vtc.yml` :)
