### ISSUE TITLE
pip install numba fails on M1 macs

### ISSUE THREAD

**Issue by kennedycasey** [MarvinLvn/voice-type-classifier#28]
Hello! Just a note to say that running `conda env create -f vtc.yml` on M1 macs returns the following error message: `Failed to build numba llvmlite`. A simple workaround is to remove the "numba==0.48.0" dependency from "vtc.yml" _and_ "pyannote-audio/requirements.txt" and then run `conda install numba` after activating the pyannote env. Hope this helps future users!

**Comment by MarvinLvn** [comment]
Arg, damn it! I haven't encountered the issue on Linux. 
Thanks a lot for finding a fix for this bug :) 
I have removed the version requirement for numba in `vtc.yml`. Let's see if this fixes the issue!
