### ISSUE TITLE
all.rttm contains files not present in others

### ISSUE THREAD

**Issue by orasanen** [MarvinLvn/voice-type-classifier#3]
Of the apply.sh outputs, CHI.rttm, FEM.rttm, KCHI.rttm, MAL.rttm, and SPEECH.rttm look sensible, but all.rttm also contains rows that correspond to files that were not transcribed in that given call of apply.sh, but on the previous (?) call. Not sure how to interpret this.

**Comment by orasanen** [comment]
There's something strange in the result files when several batches of files are processed from the same directory subsequently. Now figuring out what is exactly the problem and then reopening if needed.

**Comment by orasanen** [comment]
I've now verified that this is really the case. Even if I process only one file, the output .rttms contain detection results from several previous files that have been processed during earlier calls of apply.sh. This occurs _at least_ when the files to be processed have been located in the same folder during apply.sh (but never at the same time!). E.g., [move files to folder path/to_folder] --> [call apply.sh] --> [DELETE .wavs in path/fo_folder and move .rttms from output folder to another folder] --> [move new .wav files to folder path/to_folder] --> [call apply.sh] --> [output .rttms contain new and OLD results in the same .rttms]

**Comment by MarvinLvn** [comment]
Comes from the misuse of `>>` instead of `>` whose behavior are different.
`>>` will concatenate output while `>` will overwrite it.
It is now solved !
