### ISSUE TITLE
Issue when running "voice_type_classifier % ./apply.sh XXX"

### ISSUE THREAD

**Issue by cslawnz** [MarvinLvn/voice-type-classifier#32]
Here's the error message:

Creating config for pyannote.
Done creating config for pyannote.
./apply.sh: line 115: pyannote-audio: command not found
Something went wrong when applying the model
Aborting.

Thanks!

**Comment by MarvinLvn** [comment]
Hi, 

Did you type `conda activate pyannote` before running the `apply.sh` script?

**Comment by cslawnz** [comment]
Yep! Here’s a screenshot.

￼

Caitlyn Slawny

**Comment by cslawnz** [comment]
Hi! Yep, here's a screenshot.
<img width="789" alt="Screenshot 2024-08-22 at 12 17 17 PM" src="https://github.com/user-attachments/assets/965e8b74-7ca4-40db-8a01-23c5a47d98a5">

**Comment by MarvinLvn** [comment]
Hi there,

Hmm, it seems something went wrong during installation.
Could you please start from scratch, first deleting the conda environment and the voice_type_classifier folder:

```
conda remove -n pyannote --all
rm -rf voice_type_classifier
```

And then following the [installations instructions](https://github.com/MarvinLvn/voice-type-classifier/blob/new_model/docs/installation.md)?

If you send me a screenshot of your terminal after running the installation instructions, I'm sure we'll be able to fix your issue!

**Comment by cslawnz** [comment]
Great, that worked! Thank you!

Now I'm not sure what command to run to see the data.

<img width="891" alt="Screenshot 2024-08-29 at 11 50 42 AM" src="https://github.com/user-attachments/assets/9ff8eadd-9c75-421b-8d1f-5b93757ec7c0">

**Comment by MarvinLvn** [comment]
You can open your file manager (`Finder` if you're on MAC) and open the files as you would do with any text file! 
If this can help, [here are the slides](https://docs.google.com/presentation/d/1zs1SKic-acohLkMke2ymX65IVXBfcGj9i0blFE-04rc/edit?usp=sharing) of the tutorial I gave at IASCL 2024 (slide 19 and 20 may help)
