### ISSUE TITLE
Failure in opening a file with awk: can't open file voice_type_classifier/model/train/BBT_emp.SpeakerDiarization.All.train/validate_SPEECH/BBT_emp.SpeakerDiarization.All.development/apply/0495/LUC.SpeakerDiarization.All.test.rttm

### ISSUE THREAD

**Issue by orasanen** [MarvinLvn/voice-type-classifier#4]
Here's an error I get when I try to process 2x 2min ACLEW R1-R3 clips placed inside a folder callde LUC. As a result, I get ALL.rttm and SPEECH.rttm, but other ones are empty.  

/Users/rasaneno/Documents/koodit/voice_type_classifier/apply.sh: line 5: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
Found wav files.
Creating config for pyannote.
Done creating config for pyannote.
Extracting KCHI
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)

Test set: 0it [00:00, ?it/s]
Test set: 1it [00:26, 26.74s/it]
Test set: 2it [00:53, 26.83s/it]
Test set: 2it [00:53, 26.88s/it]

Test set: 0it [00:00, ?it/s]
Test set: 1it [00:00,  3.22it/s]
Test set: 2it [00:00,  3.40it/s]
Test set: 2it [00:00,  3.52it/s]
awk: can't open file /Users/rasaneno/Documents/koodit/voice_type_classifier/model/train/BBT_emp.SpeakerDiarization.All.train/validate_SPEECH/BBT_emp.SpeakerDiarization.All.development/apply/0495/LUC.SpeakerDiarization.All.test.rttm
 source line number 1
Extracting CHI
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)

Test set: 0it [00:00, ?it/s]
Test set: 1it [00:27, 27.46s/it]
Test set: 2it [00:53, 26.93s/it]
Test set: 2it [00:53, 26.58s/it]

Test set: 0it [00:00, ?it/s]
Test set: 1it [00:00,  3.85it/s]
Test set: 2it [00:00,  4.02it/s]
Test set: 2it [00:00,  4.15it/s]
awk: can't open file /Users/rasaneno/Documents/koodit/voice_type_classifier/model/train/BBT_emp.SpeakerDiarization.All.train/validate_SPEECH/BBT_emp.SpeakerDiarization.All.development/apply/0495/LUC.SpeakerDiarization.All.test.rttm
 source line number 1
Extracting MAL
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)

Test set: 0it [00:00, ?it/s]
Test set: 1it [00:26, 26.67s/it]
Test set: 2it [00:52, 26.46s/it]
Test set: 2it [00:52, 26.32s/it]

Test set: 0it [00:00, ?it/s]
Test set: 1it [00:00,  3.61it/s]
Test set: 2it [00:00,  3.75it/s]
Test set: 2it [00:00,  3.84it/s]
awk: can't open file /Users/rasaneno/Documents/koodit/voice_type_classifier/model/train/BBT_emp.SpeakerDiarization.All.train/validate_SPEECH/BBT_emp.SpeakerDiarization.All.development/apply/0495/LUC.SpeakerDiarization.All.test.rttm
 source line number 1
Extracting FEM
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)

Test set: 0it [00:00, ?it/s]
Test set: 1it [00:27, 27.02s/it]
Test set: 2it [00:52, 26.68s/it]
Test set: 2it [00:52, 26.46s/it]

Test set: 0it [00:00, ?it/s]
Test set: 1it [00:00,  3.67it/s]
Test set: 2it [00:00,  3.83it/s]
Test set: 2it [00:00,  3.94it/s]
awk: can't open file /Users/rasaneno/Documents/koodit/voice_type_classifier/model/train/BBT_emp.SpeakerDiarization.All.train/validate_SPEECH/BBT_emp.SpeakerDiarization.All.development/apply/0495/LUC.SpeakerDiarization.All.test.rttm
 source line number 1
Extracting SPEECH
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)

Test set: 0it [00:00, ?it/s]
Test set: 1it [00:26, 26.72s/it]
Test set: 2it [00:52, 26.44s/it]
Test set: 2it [00:52, 26.24s/it]

Test set: 0it [00:00, ?it/s]
Test set: 1it [00:00,  3.79it/s]
Test set: 2it [00:00,  3.95it/s]
Test set: 2it [00:00,  4.06it/s]

0

**Comment by MarvinLvn** [comment]
Came from incompatibility of bash 3 with associative arrays. Now fixed.
