### ISSUE TITLE
Pyannote configs are made to the folder from which apply.sh is called, not under classifier main folder. Code expects the configs to be under the main folder though.

### ISSUE THREAD

**Issue by orasanen** [MarvinLvn/voice-type-classifier#6]
I did a fresh install and ran apply.sh outside the voice_type_classifier folder the first time I called it. As a result, I got the following error (the "pyannote_tmp_config" folder was created to the current folder in bash from which apply.sh was called, not where apply.sh is located.

Found wav files.
Creating config for pyannote.
/Users/rasaneno/Documents/koodit/dists/ALICE/voice_type_classifier/apply.sh: line 42: /Users/rasaneno/Documents/koodit/dists/ALICE/voice_type_classifier/pyannote_tmp_config/database.yml: No such file or directory
/Users/rasaneno/Documents/koodit/dists/ALICE/voice_type_classifier/apply.sh: line 81: /Users/rasaneno/Documents/koodit/dists/ALICE/voice_type_classifier/pyannote_tmp_config/tmp_data.uem: No such file or directory
Done creating config for pyannote.

**Comment by orasanen** [comment]
As a hack, manually moving the pyannote_tmp_config to voice_type_classifier folder fixes the problem.

**Comment by orasanen** [comment]
Changing the code to 
    rm -rf $THISDIR/pyannote_tmp_config
    mkdir $THISDIR/pyannote_tmp_config
should do the trick. I don't have update rights to this repo so I can't change it myself.

**Comment by MarvinLvn** [comment]
Thanks Okko !
