### ISSUE TITLE
Model arguments stopped working.

### ISSUE THREAD

**Issue by orasanen** [MarvinLvn/voice-type-classifier#7]
After using the scripts for a while, voice_type_classifier stopped following the arguments for classes to extract (worked initially). I changed nothing inside the folder, but did a number of different calls of apply.sh. 

(pyannote) ws-12129-imac:ALICE rasaneno$ sh voice_type_classifier/apply.sh /Users/rasaneno/rundata/testdata_daylong/ "MAL FEM"
Found wav files.
Creating config for pyannote.
Done creating config for pyannote.
Extracting KCHI
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)
Test set: 0it [00:00, ?it/s]
...
going through all five classes.

**Comment by MarvinLvn** [comment]
Done !
